version: '3'

services:
  postgresql:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
  postgresql_data: